const SELECTED_COUNTRIES = 'selected/SELECTED_COUNTRIES';
const SELECTED_STATE = 'selected/SELECTED_STATE';
const SELECTED_CITY = 'selected/SELECTED_CITY';

export default {
  SELECTED_COUNTRIES,
  SELECTED_STATE,
  SELECTED_CITY,
};
